const hobbies: string[] = [
    "Reading",
    "Writing",
    "Painting",
    "Drawing",
    "Cooking",
    "Baking",
    "Traveling",
    "Hiking",
    "Gardening",
    "Photography",
    "Cycling",
    "Fishing",
    "Knitting",
    "Sewing",
    "Dancing",
    "Singing",
    "Playing musical instruments",
    "Swimming",
    "Yoga",
    "Meditation",
    "Gaming",
    "Woodworking",
    "Coding",
    "Collecting (stamps, coins, etc.)",
    "Running",
    "Martial arts",
    "Playing sports (e.g., soccer, basketball, tennis)",
    "Bird watching",
    "Pottery",
    "Origami",
    "Acting",
    "Learning languages",
    "Volunteering",
    "Scrapbooking",
    "DIY crafts",
    "Podcasting",
    "Blogging",
    "Vlogging",
    "Board games",
    "Card games",
    "Magic tricks",
];

export default hobbies;